---
groups:
  - name: all
    jobs:
      - get-all-public-frontend-git-repos
      - get-all-api-applications-git-repos
      - get-all-access-restricted-external-git-repos

  - name: public-frontends
    jobs:
      - get-all-public-frontend-git-repos
    resources:
      - router-git
      - static-git
      - whitehall-git
      - feedback-git
      - email-alert-frontend-git
      - info-frontend-git
      - government-frontend-git
      - service-manual-frontend-git
      - licence-finder-git
      - calendars-git
      - calculators-git
      - manuals-frontend-git
      - frontend-git
      - smart-answers-git
      - finder-frontend-git
      - collections-git

  - name: api-applications
    jobs:
      - get-all-api-applications-git-repos
    resources:
      - whitehall-git
      - support-api-git
      - router-api-git
      - content-store-git
      - rummager-git
      - email-alert-service-git
      - email-alert-api-git
      - cache-clearing-service-git
      - content-performance-manager-git
      - mapit-git
      - publishing-api-git
      - asset-manager-git
      - link-checker-git

  - name: access-restricted-external
    jobs:
      - get-all-access-restricted-external-git-repos
    resources:
      - signon-git
      - whitehall-git
      - support-git
      - contacts-admin-git
      - imminence-git
      - local-links-manager-git
      - content-data-admin-git
      - search-admin-git
      - maslow-git
      - collections-publisher-git
      - policy-publisher-git
      - content-tagger-git
      - organisations-publisher-git
      - hmrc-manuals-api-git
      - publisher-git
      - travel-advice-publisher-git
      - manuals-publisher-git
      - service-manual-publisher-git
      - specialist-publisher-git
      - content-publisher-git

resources:
  - name: router-git
    type: git
    source:
      uri: https://github.com/alphagov/router.git
      branch: master

  - name: static-git
    type: git
    source:
      uri: https://github.com/alphagov/static.git
      branch: master

  - name: whitehall-git
    type: git
    source:
      uri: https://github.com/alphagov/whitehall.git
      branch: master

  - name: feedback-git
    type: git
    source:
      uri: https://github.com/alphagov/feedback.git
      branch: master

  - name: email-alert-frontend-git
    type: git
    source:
      uri: https://github.com/alphagov/email-alert-frontend.git
      branch: master

  - name: info-frontend-git
    type: git
    source:
      uri: https://github.com/alphagov/info-frontend.git
      branch: master

  - name: government-frontend-git
    type: git
    source:
      uri: https://github.com/alphagov/government-frontend.git
      branch: master

  - name: service-manual-frontend-git
    type: git
    source:
      uri: https://github.com/alphagov/service-manual-frontend.git
      branch: master

  - name: licence-finder-git
    type: git
    source:
      uri: https://github.com/alphagov/licence-finder.git
      branch: master

  - name: calendars-git
    type: git
    source:
      uri: https://github.com/alphagov/calendars.git
      branch: master

  - name: calculators-git
    type: git
    source:
      uri: https://github.com/alphagov/calculators.git
      branch: master

  - name: manuals-frontend-git
    type: git
    source:
      uri: https://github.com/alphagov/manuals-frontend.git
      branch: master

  - name: frontend-git
    type: git
    source:
      uri: https://github.com/alphagov/frontend.git
      branch: master

  - name: smart-answers-git
    type: git
    source:
      uri: https://github.com/alphagov/smart-answers.git
      branch: master

  - name: finder-frontend-git
    type: git
    source:
      uri: https://github.com/alphagov/finder-frontend.git
      branch: master

  - name: collections-git
    type: git
    source:
      uri: https://github.com/alphagov/collections.git
      branch: master

  - name: support-api-git
    type: git
    source:
      uri: https://github.com/alphagov/support-api.git
      branch: master

  - name: router-api-git
    type: git
    source:
      uri: https://github.com/alphagov/router-api.git
      branch: master

  - name: content-store-git
    type: git
    source:
      uri: https://github.com/alphagov/content-store.git
      branch: master

  - name: rummager-git
    type: git
    source:
      uri: https://github.com/alphagov/rummager.git
      branch: master

  - name: email-alert-service-git
    type: git
    source:
      uri: https://github.com/alphagov/email-alert-service.git
      branch: master

  - name: email-alert-api-git
    type: git
    source:
      uri: https://github.com/alphagov/email-alert-api.git
      branch: master

  - name: cache-clearing-service-git
    type: git
    source:
      uri: https://github.com/alphagov/cache-clearing-service.git
      branch: master

  - name: content-performance-manager-git
    type: git
    source:
      uri: https://github.com/alphagov/content-performance-manager.git
      branch: master

  - name: mapit-git
    type: git
    source:
      uri: https://github.com/alphagov/mapit.git
      branch: master

  - name: publishing-api-git
    type: git
    source:
      uri: https://github.com/alphagov/publishing-api.git
      branch: master

  - name: asset-manager-git
    type: git
    source:
      uri: https://github.com/alphagov/asset-manager.git
      branch: master

  - name: link-checker-git
    type: git
    source:
      uri: https://github.com/alphagov/link-checker.git
      branch: master

  - name: signon-git
    type: git
    source:
      uri: https://github.com/alphagov/signon.git
      branch: master

  - name: support-git
    type: git
    source:
      uri: https://github.com/alphagov/support.git
      branch: master

  - name: contacts-admin-git
    type: git
    source:
      uri: https://github.com/alphagov/contacts-admin.git
      branch: master

  - name: imminence-git
    type: git
    source:
      uri: https://github.com/alphagov/imminence.git
      branch: master

  - name: local-links-manager-git
    type: git
    source:
      uri: https://github.com/alphagov/local-links-manager.git
      branch: master

  - name: content-data-admin-git
    type: git
    source:
      uri: https://github.com/alphagov/content-data-admin.git
      branch: master

  - name: search-admin-git
    type: git
    source:
      uri: https://github.com/alphagov/search-admin.git
      branch: master

  - name: maslow-git
    type: git
    source:
      uri: https://github.com/alphagov/maslow.git
      branch: master

  - name: collections-publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/collections-publisher.git
      branch: master

  - name: policy-publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/policy-publisher.git
      branch: master

  - name: content-tagger-git
    type: git
    source:
      uri: https://github.com/alphagov/content-tagger.git
      branch: master

  - name: organisations-publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/organisations-publisher.git
      branch: master

  - name: hmrc-manuals-api-git
    type: git
    source:
      uri: https://github.com/alphagov/hmrc-manuals-api.git
      branch: master

  - name: publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/publisher.git
      branch: master

  - name: travel-advice-publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/travel-advice-publisher.git
      branch: master

  - name: manuals-publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/manuals-publisher.git
      branch: master

  - name: service-manual-publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/service-manual-publisher.git
      branch: master

  - name: specialist-publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/specialist-publisher.git
      branch: master

  - name: content-publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/content-publisher.git
      branch: master

jobs:
  - name: get-all-public-frontend-git-repos
    serial: true
    plan:
      - get: router-git
      - get: static-git
      - get: whitehall-git
      - get: feedback-git
      - get: email-alert-frontend-git
      - get: info-frontend-git
      - get: government-frontend-git
      - get: service-manual-frontend-git
      - get: licence-finder-git
      - get: calendars-git
      - get: calculators-git
      - get: manuals-frontend-git
      - get: frontend-git
      - get: smart-answers-git
      - get: finder-frontend-git
      - get: collections-git

  - name: get-all-api-applications-git-repos
    serial: true
    plan:
      - get: whitehall-git
      - get: support-api-git
      - get: router-api-git
      - get: content-store-git
      - get: rummager-git
      - get: email-alert-service-git
      - get: email-alert-api-git
      - get: cache-clearing-service-git
      - get: content-performance-manager-git
      - get: mapit-git
      - get: publishing-api-git
      - get: asset-manager-git
      - get: link-checker-git

  - name: get-all-access-restricted-external-git-repos
    serial: true
    plan:
      - get: signon-git
      - get: whitehall-git
      - get: support-git
      - get: contacts-admin-git
      - get: imminence-git
      - get: local-links-manager-git
      - get: content-data-admin-git
      - get: search-admin-git
      - get: maslow-git
      - get: collections-publisher-git
      - get: policy-publisher-git
      - get: content-tagger-git
      - get: organisations-publisher-git
      - get: hmrc-manuals-api-git
      - get: publisher-git
      - get: travel-advice-publisher-git
      - get: manuals-publisher-git
      - get: service-manual-publisher-git
      - get: specialist-publisher-git
      - get: content-publisher-git
