---
groups:
  - name: public-frontends
    jobs:
      - build-router
      - build-static
      - build-whitehall
      - build-feedback
      - build-email-alert-frontend
      - build-info-frontend
      - build-government-frontend
      - build-service-manual-frontend
      - build-licence-finder
      - build-calendars
      - build-calculators
      - build-manuals-frontend
      - build-frontend
      - build-smart-answers
      - build-finder-frontend
      - build-collections

  - name: api-applications
    jobs:
      - build-whitehall
      - build-support-api
      - build-router-api
      - build-content-store
      - build-rummager
      - build-email-alert-service
      - build-email-alert-api
      - build-cache-clearing-service
      - build-content-performance-manager
      - build-mapit
      - build-publishing-api
      - build-asset-manager
      - build-link-checker

  - name: access-restricted-external
    jobs:
      - build-signon
      - build-whitehall
      - build-support
      - build-contacts-admin
      - build-imminence
      - build-local-links-manager
      - build-content-data-admin
      - build-search-admin
      - build-maslow
      - build-collections-publisher
      - build-policy-publisher
      - build-content-tagger
      - build-organisations-publisher
      - build-hmrc-manuals-api
      - build-publisher
      - build-travel-advice-publisher
      - build-manuals-publisher
      - build-service-manual-publisher
      - build-specialist-publisher
      - build-content-publisher

resources:
  - name: router-git
    type: git
    source:
      uri: https://github.com/alphagov/router.git
      branch: master

  - name: static-git
    type: git
    source:
      uri: https://github.com/alphagov/static.git
      branch: master

  - name: whitehall-git
    type: git
    source:
      uri: https://github.com/alphagov/whitehall.git
      branch: master

  - name: feedback-git
    type: git
    source:
      uri: https://github.com/alphagov/feedback.git
      branch: master

  - name: email-alert-frontend-git
    type: git
    source:
      uri: https://github.com/alphagov/email-alert-frontend.git
      branch: master

  - name: info-frontend-git
    type: git
    source:
      uri: https://github.com/alphagov/info-frontend.git
      branch: master

  - name: government-frontend-git
    type: git
    source:
      uri: https://github.com/alphagov/government-frontend.git
      branch: master

  - name: service-manual-frontend-git
    type: git
    source:
      uri: https://github.com/alphagov/service-manual-frontend.git
      branch: master

  - name: licence-finder-git
    type: git
    source:
      uri: https://github.com/alphagov/licence-finder.git
      branch: master

  - name: calendars-git
    type: git
    source:
      uri: https://github.com/alphagov/calendars.git
      branch: master

  - name: calculators-git
    type: git
    source:
      uri: https://github.com/alphagov/calculators.git
      branch: master

  - name: manuals-frontend-git
    type: git
    source:
      uri: https://github.com/alphagov/manuals-frontend.git
      branch: master

  - name: frontend-git
    type: git
    source:
      uri: https://github.com/alphagov/frontend.git
      branch: master

  - name: smart-answers-git
    type: git
    source:
      uri: https://github.com/alphagov/smart-answers.git
      branch: master

  - name: finder-frontend-git
    type: git
    source:
      uri: https://github.com/alphagov/finder-frontend.git
      branch: master

  - name: collections-git
    type: git
    source:
      uri: https://github.com/alphagov/collections.git
      branch: master

  - name: support-api-git
    type: git
    source:
      uri: https://github.com/alphagov/support-api.git
      branch: master

  - name: router-api-git
    type: git
    source:
      uri: https://github.com/alphagov/router-api.git
      branch: master

  - name: content-store-git
    type: git
    source:
      uri: https://github.com/alphagov/content-store.git
      branch: master

  - name: rummager-git
    type: git
    source:
      uri: https://github.com/alphagov/rummager.git
      branch: master

  - name: email-alert-service-git
    type: git
    source:
      uri: https://github.com/alphagov/email-alert-service.git
      branch: master

  - name: email-alert-api-git
    type: git
    source:
      uri: https://github.com/alphagov/email-alert-api.git
      branch: master

  - name: cache-clearing-service-git
    type: git
    source:
      uri: https://github.com/alphagov/cache-clearing-service.git
      branch: master

  - name: content-performance-manager-git
    type: git
    source:
      uri: https://github.com/alphagov/content-performance-manager.git
      branch: master

  - name: mapit-git
    type: git
    source:
      uri: https://github.com/alphagov/mapit.git
      branch: master

  - name: publishing-api-git
    type: git
    source:
      uri: https://github.com/alphagov/publishing-api.git
      branch: master

  - name: asset-manager-git
    type: git
    source:
      uri: https://github.com/alphagov/asset-manager.git
      branch: master

  - name: link-checker-git
    type: git
    source:
      uri: https://github.com/alphagov/link-checker.git
      branch: master

  - name: signon-git
    type: git
    source:
      uri: https://github.com/alphagov/signon.git
      branch: master

  - name: support-git
    type: git
    source:
      uri: https://github.com/alphagov/support.git
      branch: master

  - name: contacts-admin-git
    type: git
    source:
      uri: https://github.com/alphagov/contacts-admin.git
      branch: master

  - name: imminence-git
    type: git
    source:
      uri: https://github.com/alphagov/imminence.git
      branch: master

  - name: local-links-manager-git
    type: git
    source:
      uri: https://github.com/alphagov/local-links-manager.git
      branch: master

  - name: content-data-admin-git
    type: git
    source:
      uri: https://github.com/alphagov/content-data-admin.git
      branch: master

  - name: search-admin-git
    type: git
    source:
      uri: https://github.com/alphagov/search-admin.git
      branch: master

  - name: maslow-git
    type: git
    source:
      uri: https://github.com/alphagov/maslow.git
      branch: master

  - name: collections-publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/collections-publisher.git
      branch: master

  - name: policy-publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/policy-publisher.git
      branch: master

  - name: content-tagger-git
    type: git
    source:
      uri: https://github.com/alphagov/content-tagger.git
      branch: master

  - name: organisations-publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/organisations-publisher.git
      branch: master

  - name: hmrc-manuals-api-git
    type: git
    source:
      uri: https://github.com/alphagov/hmrc-manuals-api.git
      branch: master

  - name: publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/publisher.git
      branch: master

  - name: travel-advice-publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/travel-advice-publisher.git
      branch: master

  - name: manuals-publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/manuals-publisher.git
      branch: master

  - name: service-manual-publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/service-manual-publisher.git
      branch: master

  - name: specialist-publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/specialist-publisher.git
      branch: master

  - name: content-publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/content-publisher.git
      branch: master

jobs:
  # SHARED
  - name: build-whitehall
    serial: true
    plan:
      - get: whitehall-git

  # PUBLIC FRONTENDS
  - name: build-router
    serial: true
    plan:
      - get: router-git

  - name: build-static
    serial: true
    plan:
      - get: static-git

  - name: build-feedback
    serial: true
    plan:
      - get: feedback-git

  - name: build-email-alert-frontend
    serial: true
    plan:
      - get: email-alert-frontend-git

  - name: build-info-frontend
    serial: true
    plan:
      - get: info-frontend-git

  - name: build-government-frontend
    serial: true
    plan:
      - get: government-frontend-git

  - name: build-service-manual-frontend
    serial: true
    plan:
      - get: service-manual-frontend-git

  - name: build-licence-finder
    serial: true
    plan:
      - get: licence-finder-git

  - name: build-calendars
    serial: true
    plan:
      - get: calendars-git

  - name: build-calculators
    serial: true
    plan:
      - get: calculators-git

  - name: build-manuals-frontend
    serial: true
    plan:
      - get: manuals-frontend-git

  - name: build-frontend
    serial: true
    plan:
      - get: frontend-git

  - name: build-smart-answers
    serial: true
    plan:
      - get: smart-answers-git

  - name: build-finder-frontend
    serial: true
    plan:
      - get: finder-frontend-git

  - name: build-collections
    serial: true
    plan:
      - get: collections-git

  # API APPLICATIONS
  - name: build-support-api
    serial: true
    plan:
      - get: support-api-git

  - name: build-router-api
    serial: true
    plan:
      - get: router-api-git

  - name: build-content-store
    serial: true
    plan:
      - get: content-store-git

  - name: build-rummager
    serial: true
    plan:
      - get: rummager-git

  - name: build-email-alert-service
    serial: true
    plan:
      - get: email-alert-service-git

  - name: build-email-alert-api
    serial: true
    plan:
      - get: email-alert-api-git

  - name: build-cache-clearing-service
    serial: true
    plan:
      - get: cache-clearing-service-git

  - name: build-content-performance-manager
    serial: true
    plan:
      - get: content-performance-manager-git

  - name: build-mapit
    serial: true
    plan:
      - get: mapit-git

  - name: build-publishing-api
    serial: true
    plan:
      - get: publishing-api-git

  - name: build-asset-manager
    serial: true
    plan:
      - get: asset-manager-git

  - name: build-link-checker
    serial: true
    plan:
      - get: link-checker-git

  # ACCESS RESTRICTED EXTERNAL
  - name: build-signon
    serial: true
    plan:
      - get: signon-git

  - name: build-support
    serial: true
    plan:
      - get: support-git

  - name: build-contacts-admin
    serial: true
    plan:
      - get: contacts-admin-git

  - name: build-imminence
    serial: true
    plan:
      - get: imminence-git

  - name: build-local-links-manager
    serial: true
    plan:
      - get: local-links-manager-git

  - name: build-content-data-admin
    serial: true
    plan:
      - get: content-data-admin-git

  - name: build-search-admin
    serial: true
    plan:
      - get: search-admin-git

  - name: build-maslow
    serial: true
    plan:
      - get: maslow-git

  - name: build-collections-publisher
    serial: true
    plan:
      - get: collections-publisher-git

  - name: build-policy-publisher
    serial: true
    plan:
      - get: policy-publisher-git

  - name: build-content-tagger
    serial: true
    plan:
      - get: content-tagger-git

  - name: build-organisations-publisher
    serial: true
    plan:
      - get: organisations-publisher-git

  - name: build-hmrc-manuals-api
    serial: true
    plan:
      - get: hmrc-manuals-api-git

  - name: build-publisher
    serial: true
    plan:
      - get: publisher-git

  - name: build-travel-advice-publisher
    serial: true
    plan:
      - get: travel-advice-publisher-git

  - name: build-manuals-publisher
    serial: true
    plan:
      - get: manuals-publisher-git

  - name: build-service-manual-publisher
    serial: true
    plan:
      - get: service-manual-publisher-git

  - name: build-specialist-publisher
    serial: true
    plan:
      - get: specialist-publisher-git

  - name: build-content-publisher
    serial: true
    plan:
      - get: content-publisher-git
