---
# YAML anchors start here
unimplemented-task: &unimplemented-task-config
  config:
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: gdsre/aws-ruby
        tag: 2.6.1-3.0.1
    run:
      path: ruby
      args:
      - -e
      - |
        raise 'Unimplemented'

# Concourse starts here
groups:
  - name: public-frontends
    jobs:
      - build-router
      - build-static
      - build-whitehall
      - build-feedback
      - build-email-alert-frontend
      - build-info-frontend
      - build-government-frontend
      - build-service-manual-frontend
      - build-licence-finder
      - build-calendars
      - build-calculators
      - build-manuals-frontend
      - build-frontend
      - build-smart-answers
      - build-finder-frontend
      - build-collections

  - name: api-applications
    jobs:
      - build-whitehall
      - build-support-api
      - build-router-api
      - build-content-store
      - build-rummager
      - build-email-alert-service
      - build-email-alert-api
      - build-cache-clearing-service
      - build-content-performance-manager
      - build-mapit
      - build-publishing-api
      - build-asset-manager
      - build-link-checker

  - name: access-restricted-external
    jobs:
      - build-signon
      - build-whitehall
      - build-support
      - build-contacts-admin
      - build-imminence
      - build-local-links-manager
      - build-content-data-admin
      - build-search-admin
      - build-maslow
      - build-collections-publisher
      - build-policy-publisher
      - build-content-tagger
      - build-organisations-publisher
      - build-hmrc-manuals-api
      - build-publisher
      - build-travel-advice-publisher
      - build-manuals-publisher
      - build-service-manual-publisher
      - build-specialist-publisher
      - build-content-publisher

  - name: pipeline-tools
    jobs:
      - build-test-harness-image

resources:
  - name: test-harness-git
    type: git
    source:
      uri: https://github.com/tlwr/small-pipeline.git
      branch: master
      paths:
        - test-harness

  - name: test-harness-image
    type: docker-image
    source:
      repository: ((readonly_private_ecr_repo_url))
      tag: test-harness-latest

  - name: router-git
    type: git
    source:
      uri: https://github.com/alphagov/router.git
      branch: master

  - name: static-git
    type: git
    source:
      uri: https://github.com/alphagov/static.git
      branch: master

  - name: whitehall-git
    type: git
    source:
      uri: https://github.com/alphagov/whitehall.git
      branch: master

  - name: feedback-git
    type: git
    source:
      uri: https://github.com/alphagov/feedback.git
      branch: master

  - name: email-alert-frontend-git
    type: git
    source:
      uri: https://github.com/alphagov/email-alert-frontend.git
      branch: master

  - name: info-frontend-git
    type: git
    source:
      uri: https://github.com/alphagov/info-frontend.git
      branch: master

  - name: government-frontend-git
    type: git
    source:
      uri: https://github.com/alphagov/government-frontend.git
      branch: master

  - name: service-manual-frontend-git
    type: git
    source:
      uri: https://github.com/alphagov/service-manual-frontend.git
      branch: master

  - name: licence-finder-git
    type: git
    source:
      uri: https://github.com/alphagov/licence-finder.git
      branch: master

  - name: calendars-git
    type: git
    source:
      uri: https://github.com/alphagov/calendars.git
      branch: master

  - name: calculators-git
    type: git
    source:
      uri: https://github.com/alphagov/calculators.git
      branch: master

  - name: manuals-frontend-git
    type: git
    source:
      uri: https://github.com/alphagov/manuals-frontend.git
      branch: master

  - name: frontend-git
    type: git
    source:
      uri: https://github.com/alphagov/frontend.git
      branch: master

  - name: smart-answers-git
    type: git
    source:
      uri: https://github.com/alphagov/smart-answers.git
      branch: master

  - name: finder-frontend-git
    type: git
    source:
      uri: https://github.com/alphagov/finder-frontend.git
      branch: master

  - name: collections-git
    type: git
    source:
      uri: https://github.com/alphagov/collections.git
      branch: master

  - name: support-api-git
    type: git
    source:
      uri: https://github.com/alphagov/support-api.git
      branch: master

  - name: router-api-git
    type: git
    source:
      uri: https://github.com/alphagov/router-api.git
      branch: master

  - name: content-store-git
    type: git
    source:
      uri: https://github.com/alphagov/content-store.git
      branch: master

  - name: rummager-git
    type: git
    source:
      uri: https://github.com/alphagov/rummager.git
      branch: master

  - name: email-alert-service-git
    type: git
    source:
      uri: https://github.com/alphagov/email-alert-service.git
      branch: master

  - name: email-alert-api-git
    type: git
    source:
      uri: https://github.com/alphagov/email-alert-api.git
      branch: master

  - name: cache-clearing-service-git
    type: git
    source:
      uri: https://github.com/alphagov/cache-clearing-service.git
      branch: master

  - name: content-performance-manager-git
    type: git
    source:
      uri: https://github.com/alphagov/content-performance-manager.git
      branch: master

  - name: mapit-git
    type: git
    source:
      uri: https://github.com/alphagov/mapit.git
      branch: master

  - name: publishing-api-git
    type: git
    source:
      uri: https://github.com/alphagov/publishing-api.git
      branch: master

  - name: asset-manager-git
    type: git
    source:
      uri: https://github.com/alphagov/asset-manager.git
      branch: master

  - name: link-checker-git
    type: git
    source:
      uri: https://github.com/alphagov/link-checker.git
      branch: master

  - name: signon-git
    type: git
    source:
      uri: https://github.com/alphagov/signon.git
      branch: master

  - name: support-git
    type: git
    source:
      uri: https://github.com/alphagov/support.git
      branch: master

  - name: contacts-admin-git
    type: git
    source:
      uri: https://github.com/alphagov/contacts-admin.git
      branch: master

  - name: imminence-git
    type: git
    source:
      uri: https://github.com/alphagov/imminence.git
      branch: master

  - name: local-links-manager-git
    type: git
    source:
      uri: https://github.com/alphagov/local-links-manager.git
      branch: master

  - name: content-data-admin-git
    type: git
    source:
      uri: https://github.com/alphagov/content-data-admin.git
      branch: master

  - name: search-admin-git
    type: git
    source:
      uri: https://github.com/alphagov/search-admin.git
      branch: master

  - name: maslow-git
    type: git
    source:
      uri: https://github.com/alphagov/maslow.git
      branch: master

  - name: collections-publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/collections-publisher.git
      branch: master

  - name: policy-publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/policy-publisher.git
      branch: master

  - name: content-tagger-git
    type: git
    source:
      uri: https://github.com/alphagov/content-tagger.git
      branch: master

  - name: organisations-publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/organisations-publisher.git
      branch: master

  - name: hmrc-manuals-api-git
    type: git
    source:
      uri: https://github.com/alphagov/hmrc-manuals-api.git
      branch: master

  - name: publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/publisher.git
      branch: master

  - name: travel-advice-publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/travel-advice-publisher.git
      branch: master

  - name: manuals-publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/manuals-publisher.git
      branch: master

  - name: service-manual-publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/service-manual-publisher.git
      branch: master

  - name: specialist-publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/specialist-publisher.git
      branch: master

  - name: content-publisher-git
    type: git
    source:
      uri: https://github.com/alphagov/content-publisher.git
      branch: master

jobs:
  # SHARED

  - name: build-whitehall
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: whitehall-git
        trigger: true
      - task: run-tests
        <<: *unimplemented-task-config

  # PUBLIC FRONTENDS

  - name: build-router
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: router-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-static
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: static-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-feedback
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: feedback-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-email-alert-frontend
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: email-alert-frontend-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-info-frontend
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: info-frontend-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-government-frontend
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: government-frontend-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-service-manual-frontend
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: service-manual-frontend-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-licence-finder
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: licence-finder-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-calendars
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: calendars-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-calculators
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: calculators-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-manuals-frontend
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: manuals-frontend-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-frontend
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: frontend-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-smart-answers
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: smart-answers-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-finder-frontend
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: finder-frontend-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-collections
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: collections-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  # API APPLICATIONS

  - name: build-support-api
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: support-api-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-router-api
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: router-api-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-content-store
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: content-store-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-rummager
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: rummager-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-email-alert-service
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: email-alert-service-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-email-alert-api
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: email-alert-api-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-cache-clearing-service
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: cache-clearing-service-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-content-performance-manager
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: content-performance-manager-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-mapit
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: mapit-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-publishing-api
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: publishing-api-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-asset-manager
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: asset-manager-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-link-checker
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: link-checker-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  # ACCESS RESTRICTED EXTERNAL

  - name: build-signon
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: signon-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-support
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: support-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-contacts-admin
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: contacts-admin-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-imminence
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: imminence-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-local-links-manager
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: local-links-manager-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-content-data-admin
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: content-data-admin-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-search-admin
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: search-admin-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-maslow
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: maslow-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-collections-publisher
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: collections-publisher-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-policy-publisher
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: policy-publisher-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-content-tagger
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: content-tagger-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-organisations-publisher
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: organisations-publisher-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-hmrc-manuals-api
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: hmrc-manuals-api-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-publisher
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: publisher-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-travel-advice-publisher
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: travel-advice-publisher-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-manuals-publisher
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: manuals-publisher-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-service-manual-publisher
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: service-manual-publisher-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-specialist-publisher
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: specialist-publisher-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  - name: build-content-publisher
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: content-publisher-git
        trigger: true
      - task: tests
        <<: *unimplemented-task-config

  # PIPELINE TOOLS

  - name: build-test-harness-image
    build_logs_to_retain: 50
    serial: true
    plan:
      - get: test-harness-git
        trigger: true
      - put: test-harness-image
        params:
          build: test-harness-git/test-harness
